version = 0.1

[default.deploy.parameters]
stack_name = "CrdSam"
resolve_s3 = true
s3_prefix = "CrdSam"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "DatabaseUrl=\"arn:aws:ssm:eu-west-2:225442939245:parameter/cruddur/CONNECTION_URL\" AssetsBucketName=\"assets.cruddur.jawid.me\" AvatarUploadPrefix=\"avatar/original/\" FrontendOrigin=\"https://cruddur.jawid.me\" CorsAllowedOrigins=\"https://cruddur.jawid.me\" CognitoUserPoolId=\"eu-west-2_nYXT1Jren\" CognitoUserPoolClientId=\"vdsav0rco8m1afdqed8vo7j1i\" NetworkingStack=\"CrdNet\" DatabaseStack=\"CrdDb\" FrontendStack=\"CrdSrvFrontend\" MessagesTableName=\"cruddur-messages\" ConversationsTableName=\"cruddur-conversations\" ConnectionsTableName=\"cruddur-websocket-connections\" WebSocketApiName=\"cruddur-websocket\" StageName=\"prod\" Runtime=\"python3.12\" LogRetentionInDays=\"30\" DeletionProtection=\"true\""
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
