version = 0.1

[default.deploy.parameters]
stack_name = "CrdSAM"
resolve_s3 = true
s3_prefix = "CrdSAM"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "DatabaseUrl=\"\" AssetsBucketName=\"assets.cruddur.jawid.me\" AvatarUploadPrefix=\"avatar/original/\" CreateAssetsBucket=\"false\" FrontendOrigin=\"https://cruddur.jawid.me\" CorsAllowedOrigins=\"https://cruddur.jawid.me\" CognitoUserPoolId=\"eu-west-2_LdwGkYD5l\" CognitoUserPoolClientId=\"20usdmenjqv0nmofrkldhdnnet\" NetworkingStack=\"CrdNet\" DatabaseStack=\"CrdDb\" MessagesTableName=\"cruddur-messages\" ConversationsTableName=\"cruddur-conversations\" ConnectionsTableName=\"cruddur-websocket-connections\" WebSocketApiName=\"cruddur-websocket\" StageName=\"prod\" Runtime=\"python3.13\" LogRetentionInDays=\"30\" DeletionProtection=\"true\""
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
